export const CAP = {
  VIEW_ADMIN: "VIEW_ADMIN",

  VIEW_USERS: "VIEW_USERS",
  MANAGE_USERS: "MANAGE_USERS",

  VIEW_SETTINGS: "VIEW_SETTINGS",

  VIEW_REPORTS: "VIEW_REPORTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",

  CREATE_PROJECT: "CREATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  EDIT_PROJECT_DEADLINE: "EDIT_PROJECT_DEADLINE",
  EDIT_PROJECT_BASIC: "EDIT_PROJECT_BASIC",

  CREATE_TASK: "CREATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  EDIT_TASK_DEADLINE: "EDIT_TASK_DEADLINE",
  EDIT_TASK_BASIC: "EDIT_TASK_BASIC",
};

export const ROLE_CAPS = {
  SUPER_ADMIN: new Set([
    CAP.VIEW_ADMIN,
    CAP.VIEW_USERS,
    CAP.MANAGE_USERS,
    CAP.VIEW_SETTINGS,
    CAP.VIEW_REPORTS,
    CAP.EXPORT_REPORTS,
    CAP.CREATE_PROJECT,
    CAP.DELETE_PROJECT,
    CAP.EDIT_PROJECT_DEADLINE,
    CAP.EDIT_PROJECT_BASIC,
    CAP.CREATE_TASK,
    CAP.DELETE_TASK,
    CAP.EDIT_TASK_DEADLINE,
    CAP.EDIT_TASK_BASIC,
  ]),

  MANAGER: new Set([
    // manager should NOT see admin/users, but can manage projects/tasks
    CAP.VIEW_SETTINGS,
    CAP.VIEW_REPORTS,
    CAP.EXPORT_REPORTS,
    CAP.CREATE_PROJECT,
    CAP.DELETE_PROJECT,
    CAP.EDIT_PROJECT_DEADLINE,
    CAP.EDIT_PROJECT_BASIC,
    CAP.CREATE_TASK,
    CAP.DELETE_TASK,
    CAP.EDIT_TASK_DEADLINE,
    CAP.EDIT_TASK_BASIC,
  ]),

  HR: new Set([
    // HR can view everything except settings + report export
    CAP.VIEW_USERS,
    CAP.VIEW_REPORTS,
    CAP.EDIT_PROJECT_BASIC,
    CAP.EDIT_TASK_BASIC,
  ]),

  BUSINESS_ANALYST: new Set([
    CAP.VIEW_REPORTS,
    CAP.EDIT_PROJECT_BASIC,
    CAP.EDIT_TASK_BASIC,
  ]),

  DEVELOPER: new Set([CAP.EDIT_PROJECT_BASIC, CAP.EDIT_TASK_BASIC]),
  DESIGNER: new Set([CAP.EDIT_PROJECT_BASIC, CAP.EDIT_TASK_BASIC]),
  QA: new Set([CAP.EDIT_PROJECT_BASIC, CAP.EDIT_TASK_BASIC]),
};

// Helpers
export function can(role, cap) {
  if (!role) return false;
  const set = ROLE_CAPS[role];
  return !!set && set.has(cap);
}
